# Generated by Django 4.0.4 on 2022-07-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datalist',
            name='image',
        ),
        migrations.AddField(
            model_name='datalist',
            name='agent_contract',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='datalist',
            name='down_payment',
            field=models.CharField(default='$', max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='datalist',
            name='how_much_do_you_want_to_invest',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='datalist',
            name='signature',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
