# Generated by Django 4.0.4 on 2022-07-13 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_datalist_image_datalist_agent_contract_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datalist',
            name='agent_contract',
        ),
    ]
