# Generated by Django 4.0.4 on 2022-07-14 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_datalist_agent_contract'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataList',
        ),
    ]
