# Generated by Django 4.0.4 on 2022-06-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email_addres', models.EmailField(max_length=240, null=True)),
                ('phone_number', models.CharField(max_length=240, null=True)),
                ('agent_contract', models.CharField(max_length=240, null=True)),
                ('your_id', models.CharField(default='your national id number', max_length=16, null=True)),
                ('down_payment', models.CharField(default='$', max_length=240, null=True)),
                ('signature', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
