# Generated by Django 4.0.4 on 2022-07-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ImageField(null=True, upload_to='images/')),
                ('steel', models.CharField(default='Kg', max_length=20)),
                ('doors', models.CharField(default='Piece', max_length=20)),
                ('sand', models.CharField(default='Sacks', max_length=20)),
                ('bricks', models.CharField(default='Number', max_length=240, null=True)),
                ('aggregates', models.CharField(default='Tones', max_length=240, null=True)),
                ('stone', models.CharField(default='Tones', max_length=240, null=True)),
                ('window', models.CharField(default='Piece', max_length=16, null=True)),
                ('cement', models.CharField(default='Sacks', max_length=240, null=True)),
                ('glass', models.CharField(default='Piece', max_length=240, null=True)),
                ('metal', models.CharField(default='Piece', max_length=240, null=True)),
                ('woods', models.CharField(default='Piece', max_length=240, null=True)),
            ],
        ),
    ]
