# Generated by Django 4.0.4 on 2022-06-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='developer',
            old_name='agent_contract',
            new_name='aggregates',
        ),
        migrations.RenameField(
            model_name='developer',
            old_name='email_addres',
            new_name='bricks',
        ),
        migrations.RenameField(
            model_name='developer',
            old_name='down_payment',
            new_name='cement',
        ),
        migrations.RenameField(
            model_name='developer',
            old_name='first_name',
            new_name='doors',
        ),
        migrations.RenameField(
            model_name='developer',
            old_name='phone_number',
            new_name='glass',
        ),
        migrations.RenameField(
            model_name='developer',
            old_name='signature',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='developer',
            old_name='last_name',
            new_name='steel',
        ),
        migrations.RenameField(
            model_name='developer',
            old_name='your_id',
            new_name='window',
        ),
        migrations.AddField(
            model_name='developer',
            name='metal',
            field=models.CharField(default='$', max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='stone',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='woods',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
