# Generated by Django 4.0.4 on 2022-08-12 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='project',
        ),
    ]
