# Generated by Django 4.0.4 on 2022-06-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0002_rename_agent_contract_developer_aggregates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='cement',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='metal',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='window',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
