# Generated by Django 4.0.4 on 2022-06-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0003_alter_developer_cement_alter_developer_metal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='bricks',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
