# Generated by Django 4.0.4 on 2022-06-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0004_alter_developer_bricks'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='sand',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
