# Generated by Django 4.0.4 on 2022-07-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0005_developer_sand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='aggregates',
            field=models.CharField(default='Tones', max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='bricks',
            field=models.CharField(default='Number', max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='cement',
            field=models.CharField(default='Sacks', max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='doors',
            field=models.CharField(default='Piece', max_length=20),
        ),
        migrations.AlterField(
            model_name='developer',
            name='glass',
            field=models.CharField(default='Piece', max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='metal',
            field=models.CharField(default='Piece', max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='project',
            field=models.ImageField(null=True, upload_to='static/images/models'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='sand',
            field=models.CharField(default='Sacks', max_length=20),
        ),
        migrations.AlterField(
            model_name='developer',
            name='steel',
            field=models.CharField(default='Kg', max_length=20),
        ),
        migrations.AlterField(
            model_name='developer',
            name='stone',
            field=models.CharField(default='Tones', max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='window',
            field=models.CharField(default='Piece', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='woods',
            field=models.CharField(default='Piece', max_length=240, null=True),
        ),
    ]
