# Generated by Django 4.0.4 on 2022-07-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0006_alter_developer_aggregates_alter_developer_bricks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='project',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
