# Generated by Django 4.0.4 on 2022-07-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machmaking', '0002_remove_mach_benefit_remove_mach_contraction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mach',
            name='land_size',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
