# Generated by Django 4.0.4 on 2022-07-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machmaking', '0003_mach_land_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='mach',
            name='upi',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
