# Generated by Django 4.0.4 on 2022-07-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machmaking', '0004_mach_upi'),
    ]

    operations = [
        migrations.AddField(
            model_name='mach',
            name='benefit',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='mach',
            name='contraction',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='mach',
            name='engineer',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mach',
            name='rio',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='mach',
            name='sale_price_rwf',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mach',
            name='status',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='mach',
            name='total_cost_rwf',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='mach',
            name='unit_type',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='mach',
            name='zonning',
            field=models.CharField(choices=[('R1', 'R1'), ('R1A', 'R1A'), ('R1B', 'R1B'), ('R2', 'R2'), ('R2A', 'R2A'), ('R3', 'R3'), ('R4', 'R4'), ('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3'), ('C3A', 'C3A'), ('C3B', 'C3B'), ('C3C', 'C3C'), ('C4', 'C4'), ('C4A', 'C4A'), ('C5', 'C5'), ('I1', 'I1'), ('I2', 'I2'), ('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4')], max_length=8, null=True),
        ),
    ]
