# Generated by Django 4.0.4 on 2022-07-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machmaking', '0005_mach_benefit_mach_contraction_mach_engineer_mach_rio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mach',
            name='hello',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
