# Generated by Django 4.0.4 on 2022-07-27 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machmaking', '0006_mach_hello'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mach',
            name='hello',
        ),
    ]
