# Generated by Django 4.0.4 on 2022-07-28 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machmaking', '0008_mach_cost_sqm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mach',
            name='cost_sqm',
        ),
    ]
