# Generated by Django 4.0.4 on 2022-08-30 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='your_id',
            new_name='national_id',
        ),
    ]
