# Generated by Django 4.0.4 on 2022-07-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=240, null=True)),
                ('last_name', models.CharField(max_length=240, null=True)),
                ('email_addres', models.EmailField(default='your email address', max_length=25, null=True)),
                ('city', models.CharField(max_length=50)),
                ('location', models.CharField(default='Give /sector/district/country', max_length=240, null=True)),
                ('phone', models.CharField(default='Phone number', max_length=10)),
                ('land_size', models.PositiveSmallIntegerField(default='hectare', null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('zooning', models.CharField(choices=[('R1', 'R1'), ('R1A', 'R1A'), ('R1B', 'R1B'), ('R2', 'R2'), ('R2A', 'R2A'), ('R3', 'R3'), ('R4', 'R4'), ('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3'), ('C3A', 'C3A'), ('C3B', 'C3B'), ('C3C', 'C3C'), ('C4', 'C4'), ('C4A', 'C4A'), ('C5', 'C5'), ('I1', 'I1'), ('I2', 'I2'), ('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4')], max_length=8, null=True)),
                ('upi_number', models.CharField(max_length=20, null=True)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
