# Generated by Django 4.0.4 on 2022-08-12 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='land',
            name='city',
        ),
    ]
