# Generated by Django 4.0.4 on 2022-05-30 06:40

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0002_remove_land_city_remove_land_cost_sqm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='land',
            name='description',
        ),
        migrations.RemoveField(
            model_name='land',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='land',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='land',
            name='title',
        ),
        migrations.AddField(
            model_name='land',
            name='city',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='land',
            name='cost_sqm',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='land',
            name='email_addres',
            field=models.EmailField(default='your email address', max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='land',
            name='first_name',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='land',
            name='land_size',
            field=models.CharField(default='hectare', max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='land',
            name='last_name',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='land',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='Phone number', max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='land',
            name='upi_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='land',
            name='zooning',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
