# Generated by Django 4.0.4 on 2022-06-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0003_remove_land_description_remove_land_discount_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='land_size',
            field=models.PositiveSmallIntegerField(default='hectare', max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='phone',
            field=models.PositiveSmallIntegerField(default='Phone number', max_length=10),
        ),
    ]
