# Generated by Django 4.0.4 on 2022-06-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0004_alter_land_land_size_alter_land_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='phone',
            field=models.PositiveIntegerField(default='Phone number', max_length=10),
        ),
    ]
