# Generated by Django 4.0.4 on 2022-06-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0006_alter_land_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='location',
            field=models.CharField(default='Give /sector/district/country', max_length=240, null=True),
        ),
    ]
