# Generated by Django 4.0.4 on 2022-06-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0007_land_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='land_size',
            field=models.PositiveSmallIntegerField(default='hectare', null=True),
        ),
    ]
