# Generated by Django 4.0.4 on 2022-07-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0008_alter_land_land_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='land',
            name='cost_sqm',
        ),
        migrations.AlterField(
            model_name='land',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='land',
            name='email_addres',
            field=models.EmailField(default='your email address', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='zooning',
            field=models.CharField(choices=[('R1', 'R1'), ('R1A', 'R1A'), ('R1B', 'R1B'), ('R2', 'R2'), ('R2A', 'R2A'), ('R3', 'R3'), ('R4', 'R4'), ('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3'), ('C3A', 'C3A'), ('C3B', 'C3B'), ('C3C', 'C3C'), ('C4', 'C4'), ('C4A', 'C4A'), ('C5', 'C5'), ('I1', 'I1'), ('I2', 'I2'), ('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4')], max_length=8, null=True),
        ),
    ]
