# Generated by Django 4.0.4 on 2022-07-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0009_remove_land_cost_sqm_alter_land_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='cost_sqm',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
