# Generated by Django 4.0.4 on 2022-05-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(null=True, upload_to='images/')),
                ('title', models.CharField(max_length=120)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('address1', models.CharField(default='address1', max_length=240, null=True)),
                ('address2', models.CharField(default='address2', max_length=240, null=True)),
                ('town', models.CharField(max_length=240, null=True)),
                ('region_or_province', models.CharField(max_length=240, null=True)),
                ('country', models.CharField(max_length=240, null=True)),
                ('personal_email_address', models.EmailField(max_length=240, null=True)),
                ('mpowa_email_address', models.EmailField(max_length=240, null=True)),
                ('mobile_phone_number', models.CharField(max_length=240, null=True)),
                ('status', models.CharField(default='Live', max_length=240, null=True)),
            ],
        ),
    ]
