# Generated by Django 4.0.4 on 2022-05-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inverstor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investor',
            old_name='country',
            new_name='agent_contract',
        ),
        migrations.RenameField(
            model_name='investor',
            old_name='mpowa_email_address',
            new_name='email_addres',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='personal_email_address',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='region_or_province',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='status',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='title',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='town',
        ),
        migrations.AddField(
            model_name='investor',
            name='signature',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
