# Generated by Django 4.0.4 on 2022-06-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inverstor', '0002_rename_country_investor_agent_contract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='how_much_do_you_want_to_invest',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
