# Generated by Django 4.0.4 on 2022-07-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inverstor', '0003_investor_how_much_do_you_want_to_invest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='signature',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
